[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index-handler"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/.netlify/functions/blog-handler"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/slug-handler"
  status = 200
